name: AWS Infra CI/CD with OpenTofu

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment: dev, uat, prod'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - uat
          - prod
      
      action:
        description: 'Choose action: deploy or destroy'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - destroy

permissions:
  contents: read

env:
  AWS_REGION: us-east-1 
  WORKING_DIRECTORY: resources
  TFVARS_FILE: "../environments/democompany/us-east-1/${{ github.event.inputs.environment}}/inputs.tfvars"
  BACKEND_FILE: "../environments/democompany/us-east-1/${{ github.event.inputs.environment}}/backend.hcl"

jobs:
  # Deploy Job
  deploy:
    if: ${{ github.event.inputs.action == 'deploy' }}
    name: OpenTofu Deploy ${{ github.event.inputs.environment}}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH manually
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu Init
        run: tofu init -reconfigure -input=false -backend-config="${{ env.BACKEND_FILE }}"
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: OpenTofu Format Code
        run: tofu fmt -recursive
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: OpenTofu Format Check
        run: tofu fmt -check -recursive
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: OpenTofu Validate
        run: tofu validate
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: OpenTofu Plan
        run: tofu plan -var-file="${{ env.TFVARS_FILE }}"
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: OpenTofu Apply
        run: tofu apply -auto-approve -var-file="${{ env.TFVARS_FILE }}"
        working-directory: ${{ env.WORKING_DIRECTORY }}

  destroy:
    if: ${{ github.event.inputs.action == 'destroy' }}
    name: OpenTofu Destroy ${{ github.event.inputs.environment}}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: OpenTofu Init for safety
        run: tofu init -reconfigure -input=false -backend-config="${{ env.BACKEND_FILE }}"
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: OpenTofu Destroy
        run: tofu destroy -auto-approve -var-file="${{ env.TFVARS_FILE }}"
        working-directory: ${{ env.WORKING_DIRECTORY }}
